<a href="https://colab.research.google.com/github/abdurrahman16/Pandas-Python-library/blob/main/Pandas_Numpy_Advance_OP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('/content/sample_data/california_housing_train.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [7]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [10]:
df[df.total_rooms>1500]['total_rooms']

0        5612.0
1        7650.0
3        1501.0
6        2907.0
8        4789.0
          ...
16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 12478, dtype: float64

In [11]:
#value update
df2=df.head()

In [14]:
df2.apply(lambda x: print(x['total_rooms']), axis=1) #specific row read

5612.0
7650.0
720.0
1501.0
1454.0

0    None
1    None
2    None
3    None
4    None
dtype: object

In [20]:
def lable_status(x):
  if x['total_rooms']>7000:
    return'Double'
  else:
    return'Single'

In [22]:
df2['Category']=df2.apply(lambda x: lable_status(x), axis=1)

/tmp/ipython-input-336608396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Category']=df2.apply(lambda x: lable_status(x), axis=1)

In [23]:
df2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,Category
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,Single
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,Double
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,Single
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,Single
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,Single

In [25]:
import random
import faker

fake = faker.Faker()
n_employees = 100
departments = ["HR", "Sales", "IT", "Finance", "Marketing", "Operations", "Support"]

# Generate employee data in dictionary format
data = [
    {
        "employee_id": i,
        "name": fake.name(),
        "department": random.choice(departments),
        "age": random.randint(20, 60),
        "salary": random.randint(40000, 120000),
        "join_date": fake.date_between(start_date="-8y", end_date="today")
    }
    for i in range(1, n_employees + 1)
]

print(data[:5])  # preview first 5 employees

ModuleNotFoundError: No module named 'faker'

In [26]:
!pip install faker

Collecting faker
  Downloading faker-37.8.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from faker) (2025.2)
Downloading faker-37.8.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 38.3 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-37.8.0

In [28]:
import random
import faker

fake = faker.Faker()
n_employees = 100
departments = ["HR", "Sales", "IT", "Finance", "Marketing", "Operations", "Support"]

# Generate employee data in dictionary format
data = [
    {
        "employee_id": i,
        "name": fake.name(),
        "department": random.choice(departments),
        "age": random.randint(20, 60),
        "salary": random.randint(40000, 120000),
        "join_date": fake.date_between(start_date="-8y", end_date="today")
    }
    for i in range(1, n_employees + 1)
]

print(data[:5])  # preview first 5 employees

[{'employee_id': 1, 'name': 'Brandi Cohen', 'department': 'Sales', 'age': 58, 'salary': 72684, 'join_date': datetime.date(2022, 8, 7)}, {'employee_id': 2, 'name': 'Joseph Brown', 'department': 'Finance', 'age': 49, 'salary': 45358, 'join_date': datetime.date(2024, 4, 8)}, {'employee_id': 3, 'name': 'Anne Brown', 'department': 'Marketing', 'age': 43, 'salary': 101770, 'join_date': datetime.date(2023, 10, 1)}, {'employee_id': 4, 'name': 'Janice Ramos', 'department': 'Marketing', 'age': 44, 'salary': 63352, 'join_date': datetime.date(2023, 11, 29)}, {'employee_id': 5, 'name': 'Larry Hardin', 'department': 'Operations', 'age': 50, 'salary': 51415, 'join_date': datetime.date(2019, 8, 6)}]

In [29]:
mydata=pd.DataFrame(data)

In [30]:
mydata.head()

   employee_id          name  department  age  salary   join_date
0            1  Brandi Cohen       Sales   58   72684  2022-08-07
1            2  Joseph Brown     Finance   49   45358  2024-04-08
2            3    Anne Brown   Marketing   43  101770  2023-10-01
3            4  Janice Ramos   Marketing   44   63352  2023-11-29
4            5  Larry Hardin  Operations   50   51415  2019-08-06

In [34]:
mydata['age'].mean()

np.float64(40.51)

In [36]:
mydata['age'].isna().sum()

np.int64(0)